### ISSUE TITLE
Provider

### ISSUE THREAD

**Issue by darkzbaron** [nat/openplayground#135]
Hi what a great project, I have tried to add new provider in models.json and created custom generation functions but at the end the model does not show up in the Playground tab. Anything I am missing?

**Comment by PRANJALRANA11** [comment]
@darkzbaron  Hey, I have also created a prototype where you can compare responses of different llm's and get some feedback on it

**Comment by PRANJALRANA11** [comment]
https://llmpare.vercel.app/

**Comment by darkzbaron** [comment]
Where is the code?

**Comment by PRANJALRANA11** [comment]
not created as open source yet

**Comment by darkzbaron** [comment]
OK for anyone having this issue, this fork has azure integration https://github.com/Mat-O-Lab/openplayground
If you want to make your model appear in the Playground you need to edit parameters-side-panel and re-build
