### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by saa1028** [nat/openplayground#24]
为什么我冲了钱，用不了了？

**Comment by saa1028** [comment]
Why can't I use it after I've topped up my account?

**Comment by binglanse** [comment]
I guess there is something wrong with it now. I paied several days ago, and I found my balance become 0 today.

**Comment by clappo143** [comment]
> I paied several days ago, and I found my balance become 0 today.

Same with me

**Comment by ittalent1234** [comment]
> > 为什么我冲了钱，用不着？
> 
> 不会跑路了吧？

不知道怎么了，未知错误，感觉像跑路了

**Comment by vibl** [comment]
I get "Unknown error" too. I haven't lost my credit though.

**Comment by vibl** [comment]
Does anybody know how to alert Nat? Maybe on Twitter? https://twitter.com/natfriedman

**Comment by clappo143** [comment]
"Apologies, a disk filled up. We are fixing now."
https://twitter.com/natfriedman/status/1643993527528083458

**Comment by clappo143** [comment]
Actually, my balance has returned - seems to be resolved

**Comment by AlexanderLourenco** [comment]
Please use Discord, as this is unrelated to OSS. DM me (Alex)
