### ISSUE TITLE
I paid $5 for my another email count

### ISSUE THREAD

**Issue by mengqingmeng** [nat/openplayground#25]
I have paid $5 for my another email count in nat.dev ,but the gmail account. is there any way to refund the money?

**Comment by mengqingmeng** [comment]
I have paid $5 **TWICE** for my two email, The nat.dev still can not to use. 😭

**Comment by binglanse** [comment]
my balance shows to be 0... It seems something is wrong....

**Comment by lxnhw** [comment]
I have paid $5,but cannt to use, and the pay way is err ("Invalid product")

**Comment by mengqingmeng** [comment]
> my balance shows to be 0... It seems something is wrong....

my credit card's bill show that two pay history paid success. What should i do? ❓

**Comment by ancasarb** [comment]
same here, i paid twice the $5 and still cannot use the playground.

**Comment by mengqingmeng** [comment]
> 

my nav.dev account is still $0. where is my money?

**Comment by ZzProG** [comment]
same，so where is my money?

**Comment by AlexanderLourenco** [comment]
Please use Discord, as this is unrelated to OSS. DM me (Alex)
