### ISSUE TITLE
gpt-4 option is not the real GPT-4 model?

### ISSUE THREAD

**Issue by mike20021113** [nat/openplayground#31]
When I choose the 'gpt-4' model and just ask it 'which model are you? gpt-3 or gpt 4?' It just says that ' the model is gpt 3.5 turbo, the gpt 4 model is not released ' some kind of things, and when I compare the gpt-4 with gpt3.5-turbo, I can't find any conspicuous evidence that the gpt-4 option actually use GPT-4 model. Can somebody explain why?

**Comment by zainhuda** [comment]
LLMs don't really have information about themselves (except any hidden pre-prompts), so even if it says it's GPT-3 when asked, it really is GPT-4. So as long as you have GPT-4 selected

**Comment by mike20021113** [comment]
Thank you so much

发自我的 iPhone

在 2023年4月8日，18:17，Zain Huda ***@***.***> 写道：

﻿

LLMs don't really have information about themselves (except any hidden pre-prompts), so even if it says it's GPT-3 when asked, it really is GPT-4. So as long as you have GPT-4 selected
