### ISSUE TITLE
no models by default in the combo

### ISSUE THREAD

**Issue by sdudnic** [nat/openplayground#34]
after laucing pip and run I got the following empty interface

![image](https://user-images.githubusercontent.com/35489219/230864870-7c8d1cec-64f2-402a-b540-33a008941905.png)

so, is impossible to do anything with this

**Comment by AlexanderLourenco** [comment]
You'll need to add your API keys in settings and enable models for the UI to be filled.
We will make this more evident in the future by redirecting you to settings if no models have been enabled.

**Comment by ralyodio** [comment]
you have to create a huggingface api key to search for models.
