### ISSUE TITLE
Chat UI too limiting?

### ISSUE THREAD

**Issue by jclem** [nat/openplayground#4]
Given the existence of ChatGPT and the chat-mode completions OpenAI provides, it makes sense to be able to build a chat interface in openplayground.

However, I wonder if framing this feature as a "chat UI" is too limiting? The chat UI itself is really just a specific implementation of a stateful workflow: "process user input (in the chat case, wrap it in JSON), run completion with some history, process model output (in the chat case, parse JSON and extract/parse the response)."

Without going so far as saying "openplayground needs to be natto.dev", I wonder if there's a middle ground here.

🤔

**Comment by Kreijstal** [comment]
there is something called bettergpt that access custom api endpoint 🤷
