### ISSUE TITLE
Error building frontend app

### ISSUE THREAD

**Issue by shangqing-li** [nat/openplayground#45]
Have been running into this error below building the frontend app `npx parcel build src/index.html --no-cache`. I'm running node version 18.15. Is there any dependency that I misconfigured?

The error message is:

`Error: Invalid regular expression: /^[$_\p{ID_Start}][$_\u200C\u200D\p{ID_Continue}]*$/: Invalid property name in character class` at `/openplayground/app/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:91`

**Comment by AlexanderLourenco** [comment]
Weird, did you make any changes to the frontend code?

**Comment by zainhuda** [comment]
You can also try deleting parcel cache folder as well as node_modules folder and rebuild

**Comment by AlexanderLourenco** [comment]
Closing the issue due to inactivity. Feel free to reopen if needed.
