### ISSUE TITLE
GPT-4 is GPT-3?

### ISSUE THREAD

**Issue by SimmyXia** [nat/openplayground#51]
I found an interesting thing, when I asked GPT is GPT- 4model?He answered me that he is GPT - 3. Un....
![屏幕截图 2023-04-20 165806](https://user-images.githubusercontent.com/101860952/233317261-63563a42-7e27-44ba-9bb3-437763503e02.png)

**Comment by SimmyXia** [comment]
> even on the official chat.openai.com I get the same response whether its gpt3.5 or gpt4. LLMs don't really have information about themselves (except any hidden pre-prompts), so even if it says it's GPT-3 when asked, it really is GPT-4. So as long as you have GPT-4 selected

Thank you very much for your reply

**Comment by navyfighter12** [comment]
Welcome!

**Comment by Zhwt** [comment]
应该是 gpt-4, 你可以在 Compare 里试着问一下他国内的车牌号前缀的问题, gpt-3 给出的答案完全不对, 而且换着样的胡说八道, gpt-4 给出的结果在 temperature=0.5, p=1.0 的情况下比较稳定

> 请说出以下车牌号前缀所对应的城市：
> 黑A、辽A、鲁Q、浙B

-----

Should be gpt-4, you can try asking it about China's vehicle number plate problem and see if the answers are different. gpt-3 will output garbage while gpt-4 performs more stable when using temperature=0.5, p=1.0.
