### ISSUE TITLE
OpenAI API request was invalid: The model: `gpt-4` does not exist 

### ISSUE THREAD

**Issue by donuts-are-good** [nat/openplayground#7]
Add openAI API key

select model gpt-4

enter prompt

press submit

result: OpenAI API request was invalid: The model: `gpt-4` does not exist

**Comment by zainhuda** [comment]
do you have access to GPT-4 through OpenAI?

**Comment by txyxy** [comment]
![image](https://user-images.githubusercontent.com/31716481/229738174-96afd74a-e89c-4932-9812-86dfb3804482.png)
 I selected gpt-4 and asked this question. What's wrong?

**Comment by zainhuda** [comment]
> ![image](https://user-images.githubusercontent.com/31716481/229738174-96afd74a-e89c-4932-9812-86dfb3804482.png) I selected gpt-4 and asked this question. What's wrong?

LLMs don't really have information about themselves (except any hidden pre-prompts), so even if it says it's GPT-3 when asked, it really is GPT-4.

**Comment by donuts-are-good** [comment]
> do you have access to GPT-4 through OpenAI?

yes

**Comment by zainhuda** [comment]
@AlexanderLourenco  any idea for this error? i don't have access to gpt-4 so i cannot replicate

**Comment by navyfighter12** [comment]
Did you just get gpt4 api access? It took me about 24hrs for the api key to start working with gpt4. 
It works perfectly in openplayground.

**Comment by AlexanderLourenco** [comment]
I cannot reproduce the problem. We will change the code in settings to use OpenAI's API call to get a list of available models (specific to the API  key provided). That way, if a user cannot access GPT-4, the model won't be displayed.
