### ISSUE TITLE
Can this support cpp metal?

### ISSUE THREAD

**Issue by vdruts** [nat/openplayground#89]
Recently released for M1 inference?

**Comment by zainhuda** [comment]
This project is for running multiple models in a standardized interface. Model inference can happen in any method you'd like (external providers, local inference, etc), so yeah, we can support cpp metal. You would need to connect the inference code to the backend, and provide a text_generation method that can be called from the web interface. Take a look at documentation for adding models. It'll be very similar to that.

**Comment by vdruts** [comment]
Okay will try thanks!
